module;
#include <format>
export module vt.App.WindowEvent;

import vt.App.Window;
import vt.Core.Enum;
import vt.Core.Rect;
import vt.Core.Vector;

namespace vt
{
	export enum class KeyCode : uint8_t {
		None,
		Escape,
		F1,
		F2,
		F3,
		F4,
		F5,
		F6,
		F7,
		F8,
		F9,
		F10,
		F11,
		F12,
		F13,
		F14,
		F15,
		F16,
		F17,
		F18,
		F19,
		F20,
		F21,
		F22,
		F23,
		F24,
		Num0,
		Num1,
		Num2,
		Num3,
		Num4,
		Num5,
		Num6,
		Num7,
		Num8,
		Num9,
		Backspace,
		Enter,
		Tab,
		CapsLock,
		Shift,
		Control,
		SystemMenuLeft,
		SystemMenuRight,
		Alt,
		Space,
		Menu,
		A,
		B,
		C,
		D,
		E,
		F,
		G,
		H,
		I,
		J,
		K,
		L,
		M,
		N,
		O,
		P,
		Q,
		R,
		S,
		T,
		U,
		V,
		W,
		X,
		Y,
		Z,
		Print,
		ScrollLock,
		Pause,
		Insert,
		Delete,
		Home,
		End,
		PageUp,
		PageDown,
		ArrowLeft,
		ArrowUp,
		ArrowRight,
		ArrowDown,
		Clear,
		Decimal,
		Add,
		Subtract,
		Multiply,
		Divide,
		NumLock,
		Pad0,
		Pad1,
		Pad2,
		Pad3,
		Pad4,
		Pad5,
		Pad6,
		Pad7,
		Pad8,
		Pad9,
		AngleBracket,
		Plus,
		Comma,
		Minus,
		Period,
		OEM1,
		OEM2,
		OEM3,
		OEM4,
		OEM5,
		OEM6,
		OEM7,
		OEM8,
		WebBack,
		WebForward,
		WebRefresh,
		WebStop,
		WebSearch,
		WebFavorites,
		WebHome,
		VolumeMute,
		VolumeDown,
		VolumeUp,
		MediaNext,
		MediaPrevious,
		MediaStop,
		MediaPlayPause,
		Mail,
		MediaSelect,
		LaunchApp1,
		LaunchApp2,
	};

	export enum class MouseCode : uint8_t {
		None,
		Mouse1,
		Mouse2,
		Wheel,
		Extra1,
		Extra2,
	};

	struct WindowEvent
	{
		// The window that is related to the event.
		Window& window;

		std::string to_string() const
		{
			auto handle = reinterpret_cast<uintptr_t>(window.native_handle());
			return std::format("Window({})", handle);
		}
	};

	// Sent when a window was opened (not when a window is created).
	export struct WindowOpenEvent : WindowEvent
	{};

	// Sent when a window was closed (not when a window is destroyed).
	export struct WindowCloseEvent : WindowEvent
	{};

	// Sent when the window receives focus (i.e. clicking inside the window while it is not in focus).
	export struct WindowFocusEvent : WindowEvent
	{};

	// Sent when the window loses focus (i.e. clicking outside the window into the desktop or another window).
	export struct WindowUnfocusEvent : WindowEvent
	{};

	// Sent when the size of the window was changed.
	export struct WindowSizeEvent : WindowEvent
	{
		// The new size of the window.
		Extent const size;

		std::string to_string() const
		{
			return std::format("{}, Size({})", WindowEvent::to_string(), size.to_string());
		}
	};

	// Sent when the position of the window was changed.
	export struct WindowMoveEvent : WindowEvent
	{
		// The new position of the window.
		Int2 const position;

		std::string to_string() const
		{
			return std::format("{}, Position({})", WindowEvent::to_string(), position.to_string());
		}
	};

	struct KeyEvent : WindowEvent
	{
		// The key code associated with the interacted key.
		KeyCode const key;

		std::string to_string() const
		{
			return std::format("{}, Key({})", WindowEvent::to_string(), enum_name(key));
		}
	};

	// Sent when a key is pressed down.
	export struct KeyDownEvent : KeyEvent
	{
		// Number of times this event was generated before the key was released.
		unsigned const repeats;

		std::string to_string() const
		{
			return std::format("{}, Repeats({})", KeyEvent::to_string(), repeats);
		}
	};

	// Sent when a key is released.
	export struct KeyUpEvent : KeyEvent
	{};

	// Sent when a keystroke generates a text character.
	export struct KeyTextEvent : KeyEvent
	{
		// The text generated by the keystroke.
		std::string const text;

		std::string to_string() const
		{
			return std::format("{}, Text({})", KeyEvent::to_string(), text);
		}
	};

	// Sent when the mouse is moved.
	export struct MouseMoveEvent : WindowEvent
	{
		// The new position of the mouse in window coordinates.
		Int2 const position;

		// The direction the mouse was moved in. Positive x is right, positive y is up.
		Int2 const direction;

		std::string to_string() const
		{
			return std::format("{}, Position({}), Direction({})", WindowEvent::to_string(), position.to_string(),
							   direction.to_string());
		}
	};

	// Sent when the mouse wheel is scrolled.
	export struct MouseScrollEvent : WindowEvent
	{
		// The scrolling distance in the x and y directions, representing both horizontal and vertical scrolls.
		Float2 const offset;

		std::string to_string() const
		{
			return std::format("{}, Offset({})", WindowEvent::to_string(), offset.to_string());
		}
	};

	struct MouseClickEvent : WindowEvent
	{
		// The mouse button that was interacted with.
		MouseCode const button;

		std::string to_string() const
		{
			return std::format("{}, Button({})", WindowEvent::to_string(), enum_name(button));
		}
	};

	// Sent when a mouse button is pressed down.
	export struct MouseDownEvent : MouseClickEvent
	{};

	// Sent when a mouse button is released.
	export struct MouseUpEvent : MouseClickEvent
	{};

	// Sent when a mouse button is double-clicked.
	export struct DoubleClickEvent : MouseClickEvent
	{};
}
