module;
#include <cstdint>
export module vt.Graphics.TextureSpecification;

namespace vt
{
	export enum class ImageFormat : uint8_t {
		Unknown,
		Rgba32Float,
		Rgba32UInt,
		Rgba32SInt,
		Rgb32Float,
		Rgb32UInt,
		Rgb32SInt,
		Rgba16Float,
		Rgba16UNorm,
		Rgba16UInt,
		Rgba16SNorm,
		Rgba16SInt,
		Rg32Float,
		Rg32UInt,
		Rg32SInt,
		R32G8X24Typeless,
		D32FloatS8X24UInt,
		Rgb10A2UNorm,
		Rgb10A2UInt,
		Rg11B10Float,
		Rgba8UNorm,
		Rgba8UNormSrgb,
		Rgba8UInt,
		Rgba8SNorm,
		Rgba8SInt,
		Bgra8UNorm,
		Bgra8UNormSrgb,
		Rg16Float,
		Rg16UNorm,
		Rg16UInt,
		Rg16SNorm,
		Rg16SInt,
		R32Typeless,
		D32Float,
		R32Float,
		R32UInt,
		R32SInt,
		R24G8Typeless,
		D24UNormS8UInt,
		Rg8UNorm,
		Rg8UInt,
		Rg8SNorm,
		Rg8SInt,
		R16Typeless,
		R16Float,
		D16UNorm,
		R16UNorm,
		R16UInt,
		R16SNorm,
		R16SInt,
		R8UNorm,
		R8UInt,
		R8SNorm,
		R8SInt,
		Bc1UNorm,
		Bc1UNormSrgb,
		Bc2UNorm,
		Bc2UNormSrgb,
		Bc3UNorm,
		Bc3UNormSrgb,
		Bc4UNorm,
		Bc4SNorm,
		Bc5UNorm,
		Bc5SNorm,
		Bc6HUFloat16,
		Bc6HSFloat16,
		Bc7UNorm,
		Bc7UNormSrgb,
	};

	export enum class ImageLayout : uint8_t {
		Undefined,
		General,
		CopySource,
		CopyTarget,
		ColorAttachment,
		DepthStencilAttachment,
		DepthStencilReadOnly,
		ShaderResource,
		FragmentShaderResource,
		NonFragmentShaderResource,
		UnorderedAccess,
		Presentable,
	};

	export struct TextureSpecification
	{};
}
